target_sources(nglib PRIVATE nglib.cpp)

if(WIN32 AND NGLIB_LIBRARY_TYPE STREQUAL "STATIC")
    target_compile_definitions(nglib PUBLIC NGLIB_STATIC)
endif()

if(USE_OCC)
    target_sources(nglib PRIVATE nglib_occ.cpp)
    install(FILES nglib_occ.h DESTINATION ${NG_INSTALL_DIR_INCLUDE} COMPONENT netgen_devel)
endif(USE_OCC)

if(NETGEN_NATIVE_SDK)
    target_link_libraries(nglib PRIVATE "$<BUILD_INTERFACE:${ZLIB_LIBRARIES}>")
    target_link_libraries( nglib PUBLIC ngcore PRIVATE ${CMAKE_THREAD_LIBS_INIT} ${JPEG_LIBRARIES} ${MKL_LIBRARIES} "$<BUILD_INTERFACE:occ_libs>" )
else()
    target_link_libraries(nglib PRIVATE ${ZLIB_LIBRARIES})
    target_link_libraries( nglib PUBLIC ngcore PRIVATE ${CMAKE_THREAD_LIBS_INIT} ${JPEG_LIBRARIES} ${MKL_LIBRARIES} occ_libs netgen_cgns )
endif()

if(NETGEN_NATIVE_SDK)
    install(TARGETS nglib ${NG_INSTALL_DIR})
else()
    install(TARGETS nglib netgen_cgns ${NG_INSTALL_DIR})
endif()
install(FILES nglib.h DESTINATION ${NG_INSTALL_DIR_INCLUDE} COMPONENT netgen_devel)
